include:
  - "/assets/images/favicon.ico"

theme: jekyll-theme-minimal
logo: "/assets/images/favicon.png"
title: "Find my next course - by Inference"
description: "A web application designed to help students explore KTHâ€™s course offerings."
